// Content script - runs on blog.google pages

function extractPageText() {
  // Clone the HTML and parse it fresh
  const doc = new DOMParser().parseFromString(document.body.innerHTML, 'text/html');

  // Remove non-content elements
  const removeSelectors = [
    'script', 'style', 'nav', 'header', 'footer', 'noscript',
    'button', 'input', 'select', 'textarea', 'form',
    '[role="button"]', '[role="navigation"]',
    // Cookie/consent banners
    '[class*="cookie"]', '[class*="consent"]', '[id*="cookie"]',
    // Social share
    '[class*="share"]', '[class*="social"]', 'a[href*="x.com"]', 'a[href*="facebook"]', 'a[href*="linkedin"]',
    // Media players
    'audio', 'video', '[class*="audio"]', '[class*="video"]', '[class*="player"]',
    // Related content
    '[class*="related"]', '[class*="recommended"]',
    // Newsletter/subscribe
    '[class*="newsletter"]', '[class*="subscribe"]',
    // Footnotes/disclaimers
    '[class*="footnote"]', '[class*="disclaimer"]',
    // Sidebar
    'aside', '[role="complementary"]'
  ];
  doc.querySelectorAll(removeSelectors.join(', ')).forEach(el => el.remove());

  let text = doc.body.innerText;

  // Remove specific boilerplate patterns (conservative)
  const noisePatterns = [
    /Sorry, your browser doesn't support embedded videos[^.]*\./gi,
    /Your browser does not support the audio element\.?/gi,
    /Listen to article.*?minutes/gi,
    /This content is generated by Google AI\. Generative AI is experimental/gi,
    /\d+:\d+\s+minutes\s+\d+:\d+\s+\d+:\d+/g, // audio player timestamps
    /x\.com\s+Facebook\s+LinkedIn\s+Mail/gi, // social share row
    /Let's stay in touch\. Get the latest news.*?Subscribe/gi,
    /uses cookies.*?Learn more/gi,
  ];

  for (const pattern of noisePatterns) {
    text = text.replace(pattern, '');
  }

  return text.replace(/\s+/g, ' ').trim();
}

const pageText = extractPageText();
console.log('Extracted text length:', pageText);